repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: detect-private-key

  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform fmt
        description: runs terraform fmt
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: terraform-docs
        name: terraform-docs
        description: runs terraform-docs
        entry: terraform-docs -c .terraform-docs.yml .
        language: system
        pass_filenames: false

  # - repo: git://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.29.0
  #   hooks:
  #     - id: markdownlint

  # - repo: git://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.56.0
  #   hooks:
  #     - id: terraform_docs
  #     - id: terraform_fmt
  #     - id: terraform_validate
